Include jinja2 templates in the build artifact
hypothesis/pyramid-googleauth pull request #7
Opened 2022-08-15 11:11 UTC by marcospri

Previous commit removed MANIFEST which included templates as part of the
build.

Using a different mechanism here that can be specified directly in
setup.cfg

https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data

2022-08-16 11:16 UTC, seanh requested changes
`pip` tip: you can `pip install` directly from a branch of a GitHub repo, this way the user doesn't need to check out the branch in a local copy of `pyramid-googleauth` just to install it in Checkmate: `.tox/functests/bin/pip install git+https://github.com/hypothesis/pyramid-googleauth.git@include-templates` (but this is not an editable install).

The fix works for me locally :+1:

Good job we have functests as unit tests would not catch template problems.

This will collide with the cookiecutter because `setup.cfg` is a templated file:

```terminal
$ make template
$ git diff
diff --git a/setup.cfg b/setup.cfg
index 0505a48..c2f8f77 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -25,10 +25,6 @@ install_requires =
 [options.packages.find]
 where = src

-[options.package_data]
-pyramid_googleauth =
-    templates/*
-
 [options.entry_points]

 [pycodestyle]
```

The fix is to move the new stuff into `.cookiecutter/includes/setup.cfg` and then re-run `make template`:

```diff
diff --git a/.cookiecutter/includes/setup.cfg b/.cookiecutter/includes/setup.cfg
new file mode 100644
index 0000000..fb4b9e5
--- /dev/null
+++ b/.cookiecutter/includes/setup.cfg
@@ -0,0 +1,4 @@
+
+[options.package_data]
+pyramid_googleauth =
+    templates/*
diff --git a/setup.cfg b/setup.cfg
index 0505a48..0867440 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -25,10 +25,6 @@ install_requires =
 [options.packages.find]
 where = src
 
-[options.package_data]
-pyramid_googleauth =
-    templates/*
-
 [options.entry_points]
 
 [pycodestyle]
@@ -46,3 +42,7 @@ ignore =
 
     # Bare except. PyLint finds these for us so we don't need pycodestyle to.
     E722,
+
+[options.package_data]
+pyramid_googleauth =
+    templates/*
```

2022-08-17 09:15 UTC, marcospri commented
Thanks @seanh, just adapted this to use the templating :+1:

2022-08-17 10:01 UTC, seanh approved these changes, later dismissed

2022-08-17 10:01 UTC, seanh commented on setup.cfg
> +[options.package_data]
If you want a blank line between the `[pycodestyle]` section in `setup.cfg` (`E722`) and this then `.cookiecutter/includes/setup.cfg` needs to start with a blank line.

(This is true of many of the includes files. I couldn't figure out a better way to implement it. For example I couldn't get it to work exactly right by using Jinja2's "whitespace control" feature. When an include file does exist you'll often want a blank line before its contents but when the same include file does not exist then you don't want to render an extra blank line.)

2022-08-17 10:02 UTC, seanh commented
`make template` runs cleanly for me :+1:

2022-08-17 10:24 UTC, merged